### PR TITLE
Update ru.txt from 20211115

### PR DESCRIPTION
**Pull request by ViktorOn**
Correcting translation and adding translation of some strings

### CODE REVIEW

**Review by peazip — APPROVED** [review]

**Comment by ViktorOn** [comment]
I've made so many corrections, including spelling, and now many of the mistakes are back in place! Why?

**Comment by peazip** [comment]
I've received a new translation by mail 17 of november, and then merged it in GitHub.
I'm sorry for the inconvenient and I'll proceed to restore your translation.
For the future I'll give higher priority to updates via GitHub, because are easier to track and discuss.

**Comment by ViktorOn** [comment]
> I've received a new translation by mail 17 of november, and then merged it in GitHub. I'm sorry for the inconvenient and I'll proceed to restore your translation. For the future I'll give higher priority to updates via GitHub, because are easier to track and discuss.

I hope this process will get better. And I will be able to help with the translation normally.

**Comment by ViktorOn** [comment]
I checked again. The best option is to change the lines 10, 11, 13, 14, 15, 16 and 19 in my translation in accordance with the one sent to you by mail. 👍🏻

**Comment by peazip** [comment]
Thank you for the further feedback, I've applied the changes you suggested.
In future if a translator will contribute by mail a language file already existing for the same language / release, I'll recommend to partecipate using GitHub commits, due the collaborative nature of the platform allowing more efficient control of changes introduced.

**Pull request merged**
