### PR TITLE
Improve readability

### PR DESCRIPTION
**Pull request by ddzzkunye**
提高可读性\统一性

### CODE REVIEW

**Comment by jyhi** [comment]
Hi @ddzzkunye ! Just want to let you know that there has been work on the translation in [this repository](https://github.com/jyhi/PeaZip-l10n-zh-Hans). If you could consider submitting your improvement to that repository then we can avoid a lot of repeated / synchronisation work. More people can review your work too. Thanks :)

**Comment by ddzzkunye** [comment]
> Hi @ddzzkunye ! Just want to let you know that there has been work on the<details> translation in [this repository](https://github.com/jyhi/PeaZip-l10n-zh-Hans). <details>If you could consider submitting your improvement to that repository then we can avoid a lot of repeated / synchronisation work. More people can review your work too. Thanks :)</details>

okay, I know 

Well, I looked at the repository you mentioned , and it's still in version 9.2  

I'm just an ordinary user.  
~~By the way, I just started learning git~~  
If you have a better way, be sure to let me know, very grateful!

**Comment by Chaython** [comment]
BTW 9.3 32 bit windows executable in the release is detected as a trojan by multiple engines.
Despite only having 4 engines detect it as a virus, many more detect the latest push on chocolatey as a virus including but not limited to Kaspersky. Similar detections by winget stopped 9.3 from ever being pushed also[?]

image

https://www.virustotal.com/gui/file/63a2ba1ed38d972b6f8211f6e125193270b7ebce6217bc219087c9a5604ddc7a

Sorry, I don't see anywhere to create an issue etc...

**Comment by jyhi** [comment]
@Chaython Without Giorgio opening the issue tab you could only send an email to [giorgio.tani.software@gmail.com](mailto:giorgio.tani.software@gmail.com). Thank you :|

**Comment by jyhi** [comment]
@ddzzkunye 请问是否能够提供这些更改在软件中的位置？这些字串是在首次出现后被修改过的，所以产生了严重的不正确，但是我暂时找不到他们出现在什么地方 :(

<details>
<summary>Translation</summary>
<p>@ddzzkunye Could you please provide the location of the changes in the software? These strings were changed after their first appearance, so they created serious incorrectness, but I cannot find where do they appear so far :(</p>
</details>

**Comment by jyhi** [comment]
With works going on in another repository this PR can be closed.

**Pull request closed without merging**
