### PR TITLE
Update pt-pt.txt

### PR DESCRIPTION
**Pull request by smarquespt**
@hugok79

### CODE REVIEW

**Comment by hugok79** [comment]
@smarquespt Estou no telemóvel mas do que vi a tradução parece-me bem. Apenas detetei um erro ortográfico na linha 16, nomeadamente a palavra "comenado". Que será comando. Ou se calhar até devia ser "linha de comandos".

**Comment by hugok79** [comment]
@peazip Don't merge yet. There is a typo in a word as such lets wait for @smarquespt to fix.

**Comment by smarquespt** [comment]
@hugok79 Thanks
@peazip Fixed

**Comment by hugok79** [comment]
@smarquespt You always save your translations with UTF-8-BOM ? See image below:

Captura de ecrã 2022-09-16 162538

**Comment by smarquespt** [comment]
@hugok79 Usually I translate strings directly in Github, not using Notepad++.

**Comment by hugok79** [comment]
@smarquespt Ok, thanks. I asked you this because when using the portable version of peazip 8.8.0 for the first time and after changing the language to portuguese **pt-pt,** the program was still in English.
Here https://sourceforge.net/p/peazip/tickets/705/ I found the solution to the problem.
The version 8.7.0 did not have this problem.

**Pull request merged**
